### ISSUE TITLE
Export object-to-react at a top level

### ISSUE THREAD

**Issue by rgbkrk** [remarkablemark/REON#5]
The primary part of REON I want to use is `object-to-react`, which I've used in the past within nteract like this: https://github.com/nteract/nteract/pull/1212/files

Could you export that as an individual package?

**Comment by remarkablemark** [comment]
@rgbkrk That's definitely doable but do you think it makes sense for `REON` to expose a method like `parseObject()` instead of creating another package?

**Comment by rgbkrk** [comment]
That's fine too.

**Comment by remarkablemark** [comment]
@rgbkrk You can find `parseObject` in [v0.1.0](https://github.com/remarkablemark/REON/tree/v0.1.0):
```sh
# npm
npm install reon-core@0.1.0

# yarn
yarn add reon-core@0.1.0
```
